 # Right Shif an Array

 # Problem dicscription 

 Write a program that reads an integer array A from input and modifies the array by shifting 
 each element to the right by one position and by shifting the last element to the first position.

 return the modified array 

 Problem contraints 
 1<=N<=10^5
 1<=A(i)<=10^9

 # Input Format
 The first of the input is the size of the array N. The seconf line of the input is N integers of the array seper ated by space.

 # Output Format 
 Print a single line that is the elemnts of the modified array seperated by space.

 Example input 

 5
 1 2 3 4 5

 Example output 

 5 1 2 3 4 

 



In [14]:
'''
To right shift an array in Python without using any libraries, 
you can use a simple approach using basic list operations:
'''

'''
Here, the insert() method is used to insert the popped element from the end of the list to 
the beginning of the list shift_count number of times. 
This essentially shifts the array to the right by shift_count positions.

In the example above, the output will be [4, 5, 1, 2, 3], 
which is the original array shifted to the right by 1 positions.
'''

# Solution and Aproch to the problem

# Creat sample array 
arr = [1, 2, 3, 4, 5]

# number of posiotn to shift the array to the right
shift_count = 1

# right shift the array 
for i in range(shift_count):
    arr.insert(0, arr.pop())

print(arr)


[5, 1, 2, 3, 4]


In [16]:
# list slicing approach 
lst = [1, 2, 3, 4, 5]
[lst[-1]] + lst[:4]

[5, 1, 2, 3, 4]

In [18]:
lst = [1, 2, 3, 4, 5]
for i in range(len(lst)):
    print(lst[i-1], end=" ")

5 1 2 3 4 

In [11]:
lst = [1, 2, 3, 4, 5, 6]
last_ele = lst.pop()
lst.insert(0, last_ele)
for i in lst:
    print(i, end=" ")

6 1 2 3 4 5 

In [3]:
# Problem 2 => How to add two matrix ?

# program for addition of matrix  using for loop

mat1 = [[1, 3, 6], [5, 4, 6], [6, 4, 9]]
mat2 = [[5, 6, 1], [3, 5, 7], [8, 5, 7]]

res = [[0,0,0], [0,0,0], [0,0,0]]
rows = len(mat1)
cols  = len(mat1[0])

#iterate through rows 
for i in range(len(mat1)):
# iterate through columns
    for j in range(len(mat1[0])):
        res[i][j] = mat1[i][j] + mat2[i][j]
for r in res:
    print(r)

[6, 9, 7]
[8, 9, 13]
[14, 9, 16]


In [14]:
# Problem 2 => How to add two matrix ?

# program for addition of matrix  using for loop

mat1 = [[1, 3, 6], [5, 4, 6], [6, 4, 9]]
mat2 = [[5, 6, 1], [3, 5, 7], [8, 5, 7]]

res = []
rows = len(mat1)
cols  = len(mat1[0])

#iterate through rows 
for i in range(rows):
    row = []
# iterate through columns
    for j in range(cols):
        row.append(mat1[i][j] + mat2[i][j])
    res.append(row)
print(res)

[[6, 9, 7], [8, 9, 13], [14, 9, 16]]


In [1]:

# program for addition of matrix  using zip()

#Here, list(map(sum, zip(*t))) computes the element-wise sum of the rows in mat1 and mat2 using the map() function and the sum() function. 
# The resulting map object is then converted to a list using the list() function. 

mat1 = [[1, 3, 6], [5, 4, 6], [6, 4, 9]]
mat2 = [[5, 6, 1], [3, 5, 7], [8, 5, 7]]

res = [list(map(sum, zip(*t))) for t in zip(mat1, mat2)]
print(res)


[[6, 9, 7], [8, 9, 13], [14, 9, 16]]


In [1]:
# let's use numpy to add to matrix

import numpy as np

mat1 = [[1, 3, 6], [5, 4, 6], [6, 4, 9]]
mat2 = [[5, 6, 1], [3, 5, 7], [8, 5, 7]]

result = np.array(mat1) + np.array(mat2)
print(result)

[[ 6  9  7]
 [ 8  9 13]
 [14  9 16]]


In [ ]:
# Identity Matrix
# https://www.geeksforgeeks.org/python-matrix/
'''Introduction to Identity Matrix :

 The dictionary definition of an Identity Matrix is a square matrix in which all 
 the elements of the principal or main diagonal are 1’s and all other elements are zeros. 
 In the below image, every matrix is an Identity Matrix. 
 
 '''


In [18]:
# program to check whether given matrix is identiy or not
a = [[1,0,0], [0,1,0], [0,0,1]]
for i in range(len(a)):
    for j in range(len(a[0])):
        if i == j:
            print(a[i][j])



1
1
1


In [24]:
def identity_matrix(a, n):
    for i in range(n):
        for j in range(n):
            if i == j and a[i][j] != 1: # if it is diagonal element chek it is 0 or not
                return False
            elif i!=j and a[i][j] !=0: # if it is non-diagonal element chek it is 0 or not
                return False
    return True
a = [[1,0,1], [0,1,0], [0,0,1]]
identity_matrix(a, 3)

False

In [25]:
# Frequency of charecter in string
string  =  "authobiography of mahatma gandhi"
dictionary  = {}
for i in string:
    dictionary[i] = string.count(i)

print(dictionary)

{'a': 6, 'u': 1, 't': 2, 'h': 4, 'o': 3, 'b': 1, 'i': 2, 'g': 2, 'r': 1, 'p': 1, 'y': 1, ' ': 3, 'f': 1, 'm': 2, 'n': 1, 'd': 1}


In [28]:
string = "interstellar"
dictionary = {}
for i in string:
    if dictionary.get(i):
        dictionary[i] += 1
    else:
        dictionary[i] = 1
print(dictionary)


{'i': 1, 'n': 1, 't': 2, 'e': 2, 'r': 2, 's': 1, 'l': 2, 'a': 1}
